kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: "{{ mac_fix_ds_name }}"
  namespace: "{{ ansible_operator_meta.namespace }}"
spec:
  selector:
    matchLabels:
      name: "{{ mac_fix_ds_name }}"
  template:
    metadata:
      labels:
        name: "{{ mac_fix_ds_name }}"
    spec:
      restartPolicy: Always
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
      - name: testpmd-mac-fix
        image: "{{ mac_workaround_image }}"
        imagePullPolicy: "{{ image_pull_policy }}"
        securityContext:
          privileged: true
        environments:
          MAC_WORKAROUND_VERSION: "{{ mac_workaround_version }}"
          MAC_WORKAROUND_FILE: "{{ mac_workaround_file }}"
        volumeMounts:
        - name: host-cni-bin
          mountPath: /hostbin
        lifecycle:
          postStart:
            exec:
              command: ["echo Hello from the postStart handler"]
          preStop:
            exec:
              command: ["echo Hello from the preStop handler"]
        terminationMessagePolicy: FallbackToLogsOnError
      volumes:
      - name: host-cni-bin
        hostPath:
          path: /var/lib/cni/bin
